### ISSUE TITLE
what can cause NoSuchMethodError ?

### ISSUE THREAD

**Issue by MarwenSami** [psycopaths/jconstraints-z3#3]
Hello,
I want to know what can cause this kind of error:

> Exception in thread "main" java.lang.NoSuchMethodError: com.microsoft.z3.Solver.getUnsatCore()[Lcom/microsoft/z3/Expr;
>         at gov.nasa.jpf.constraints.solvers.nativez3.NativeZ3SolverContext.solve(NativeZ3SolverContext.java:102)
>         at gov.nasa.jpf.jdart.constraints.InternalConstraintsTree.findNext(InternalConstraintsTree.java:466)
>         at gov.nasa.jpf.jdart.ConcolicMethodExplorer.hasMoreChoices(ConcolicMethodExplorer.java:206)
>         at gov.nasa.jpf.jdart.ConcolicExplorer.hasMoreChoices(ConcolicExplorer.java:206)
>         at gov.nasa.jpf.jdart.JDartChoiceGenerator.hasMoreChoices(JDartChoiceGenerator.java:64)
>         at gov.nasa.jpf.vm.SystemState.advanceCurCg(SystemState.java:883)
>         at gov.nasa.jpf.vm.SystemState.initializeNextTransition(SystemState.java:745)
>         at gov.nasa.jpf.vm.VM.forward(VM.java:1709)
>         at gov.nasa.jpf.search.Search.forward(Search.java:579)
>         at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
>         at gov.nasa.jpf.JPF.run(JPF.java:613)
>         at gov.nasa.jpf.jdart.JDart.run(JDart.java:207)
>         at gov.nasa.jpf.jdart.JDart.start(JDart.java:131)
>         at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:108)

I think that this occurs when a path cannot be resolved logically (no concrete solution), I'm not really sure about that, if that turns out to be true, I need to know what else can cause this exception.

Best regards,

**Comment by fhowar** [comment]
Looks like you are using a com.microsoft.z3.jar (and probably a z3 version) that are incompatible with the current version of Jdart. Can you post some information about the z3 version and jar?

Thanks 

  Falk

**Comment by MarwenSami** [comment]
Hello fhowar,
I'm using Z3 v4.4.1, compiled on a windows 8.1 x64 machine.

**Comment by fhowar** [comment]
The interface of Solver.java changed between versions 4.4.0 and 4.4.1 of Z3

in 4.4.1 the method signature of getUnsatCore is  
`public BoolExpr[] getUnsatCore()`

Up until 4.4.0 the signature was 
`public Expr[] getUnsatCore()`

There are two (alternative) quick workarounds for your problem

1) You switch to Z3 4.4.0 - OR -
2) You change line 102 in NativeZ3SolverContext.java locally to expect BoolExpr instead of Expr.

I am not sure how to address this issue in jconstraints-z3 currently other than by naming a specific version of Z3 (i.e., 4.4.0) as dependency.

**Comment by MarwenSami** [comment]
Thanks fhowar for the reply, indeed it fixed the issue ;)
I suggest that you stick with the v4.4.1 and fix the issue in NativeZ3SolverContext.java, @ksluckow already updated the dependency few days ago on a previous issue.
Don't know the consequences though.
Thank you anyway it was helpful.

**Comment by ksluckow** [comment]
Hmm, I'm not sure what the issue is at the moment. Which version works for you @MarwenSami?
Z3 4.4.1 works with jConstraints-z3. However, the `master` branch of Z3 does **not** work.

The culprit of `java.lang.NoSuchMethodError` is usually when the class you have compiled against, is different from the class you use at runtime. In other words, your classpath on compile time likely includes a different version of the z3 java bindings (`com.microsoft.z3.jar`) than the z3 java bindings you have on your classpath at runtime. You must have had the "correct" `com.microsoft.z3.jar` when you compiled jconstraints-z3, otherwise the compilation would have failed.

This is, unfortunately, a very common problem for JPF-related projects, because all the JPF modules included in the `extensions` variable in your `~/.jpf-properties` file are added to the runtime classpath. For example, a very common scenario is to also have `jpf-symbc` installed.
If you followed its installation instruction (specifically added `jpf-symbc` to the `extensions` variable), you will have `jpf-symbc/lib/com.microsoft.z3.jar` on your classpath **in addition** to `com.microsoft.z3.jar` from `~/.jconstraints/extensions`.

Please check where `gov.nasa.jpf.constraints.solvers.nativez3.NativeZ3SolverContext` is loaded to ensure that you are indeed using the intended z3 4.4.1 `com.microsoft.z3.jar`. You can do that by passing the `-verbose` option to the `java` program (e.g. just add it to the script `jpf-core/bin/jpf`). It will list all classes loaded by the classloader.

**Comment by fhowar** [comment]
It works until you hit an unsatisfiable branch. In which case we call 

`for (Expr e : solver.getUnsatCore()) {
   logger.finest("  " + e.getSExpr());
 }`

[link to code](https://github.com/psycopaths/jconstraints-z3/blob/ae33390323d84f97516c80652cebdf6116b67107/src/main/java/gov/nasa/jpf/constraints/solvers/nativez3/NativeZ3SolverContext.java#L102-L104)

In Z3 version 4.4.1 `getUnsatCore()` returns a `BoolExpr`. This is why the method lookup fails (looking for a method that returns `Expr`).

I think, since we list Z3 version 4.4.1 as a dependency, we should change the for loop to iterate over `BoolExpr`.

**Comment by MarwenSami** [comment]
As @fhowar said it the problem was with the return type of getUnsatCore(), I changed it from Expr  to BoolExpr and recompiled and everything works great !

Best regards,
