### ISSUE TITLE
Reals stopped working with z3-4.1.1

### ISSUE THREAD

**Issue by fhowar** [psycopaths/jconstraints-z3#6]
For no apparent reason, reals do not work after I updated z3. Here is some code to check reproducibility:

```
public class DoubleTest {

    @Test
    public void expressionTest() throws RecognitionException {

        Properties conf = new Properties();
        conf.setProperty("symbolic.dp", "NativeZ3");

        Variable<Double> s1 = Variable.create(BuiltinTypes.DOUBLE, "s1");
        Variable<Double> s2 = Variable.create(BuiltinTypes.DOUBLE, "s2");
        Variable<Double> r1 = Variable.create(BuiltinTypes.DOUBLE, "r1");

        Constant<Double> c0 = Constant.create(BuiltinTypes.DOUBLE, 0.0);
        Constant<Double> c1 = Constant.create(BuiltinTypes.DOUBLE, 1.0);

        ConstraintSolverFactory factory = new ConstraintSolverFactory(conf);
        ConstraintSolver solver = factory.createSolver();

        //(assert (< s2 r1))
        //(assert (> s2 s1))
        //(assert (= 1.0 r1))
        //(assert (= 0.0 s1))
        //(assert (not (= 0.0 s2)))
        //(assert (not (= 1.0 s2)))    
        Expression<Boolean> expr = ExpressionUtil.and(
                new NumericBooleanExpression(s2, NumericComparator.LT, r1),
                new NumericBooleanExpression(s2, NumericComparator.GT, s1),
                new NumericBooleanExpression(r1, NumericComparator.EQ, c1),
                new NumericBooleanExpression(s1, NumericComparator.EQ, c0),
                new NumericBooleanExpression(s2, NumericComparator.NE, c0),
                new NumericBooleanExpression(s2, NumericComparator.NE, c1)
        );

        System.out.println(expr.toString(3));

        Valuation val = new Valuation();
        ConstraintSolver.Result result = solver.solve(expr, val);
        System.out.println(result);
        System.out.println(val);

        Assert.assertEquals(result, Result.SAT);
    }
}
```

s2 is supposed to be between 0.0 and 1.0 (both bounds exclusive). 

With my setup, z3 returns unsat.

I added some debug spam. It seems that all variables are created of sort Real in z3.

**Comment by fhowar** [comment]
Can somebody (@ksluckow or @mmuesly or  @mdimjasevic maybe?) try to reproduce the behavior with the same or another version of z3?

**Comment by ksluckow** [comment]
Hi Falk. I also get unsat with jconstraints and z3 4.4.1.
I checked with z3 (again v. 4.4.1) the formula

```
(declare-const s1 Real)
(declare-const s2 Real)
(declare-const r1 Real)

(assert (< s2 r1))
(assert (> s2 s1))
(assert (= r1 1.0))
(assert (= s1 0.0))
(assert (not (= s2 0.0)))
(assert (not (= s2 1.0)))
(check-sat)
```

and I get sat.

I'm a bit busy today, but maybe I can take a look later.

**Comment by fhowar** [comment]
Malte and I went through the z3 java code and also through the generated native interface. The z3 part seems fine. Also, running the following code against the API works as expected

```
    @Test
    public void testZ3RealsJava() {
        Context ctx = new Context();
        RealExpr s2 = ctx.mkRealConst("s2");
        RatNum c0 = ctx.mkReal("0.0");
        RatNum c1 = ctx.mkReal("1.0");

        BoolExpr test = ctx.mkAnd(
                ctx.mkGt(s2, c0),
                ctx.mkLt(s2, c1)
        );

        System.out.println(test);
        Solver solver = ctx.mkSolver();
        solver.add(test);
        Status status = solver.check();
        Assert.assertEquals(status, Status.SATISFIABLE);
    }
```

(I ran a minimal version for the original code as well: still UNSAT)

I tried commenting out the generation of bounds for variables by jconstraints-z3 (to no avail) and checked that all variables and constants are generated as reals (seems to be the case).

Maybe it has to do with incremental solving or some other thing that we add to the context?

**Comment by fhowar** [comment]
So, in the z3 code above, when I push before I add `expr`, the result turns to unsat:

```
       ...
        System.out.println(test);
        Solver solver = ctx.mkSolver();
        solver.push();        
        solver.add(test);
        Status status = solver.check();
```

**Comment by fhowar** [comment]
Some further testing suggests that it hinges on the push. 
It doesn't happen in the rise4fun version:

```
(declare-fun s2 () Real)
(push)
(assert (and (> s2 0.0) (< s2 1.0) ))
(check-sat)
(get-model)
(exit) 
```

**Comment by mmuesly** [comment]
I could reproduce Falks error. Then I build the current HEAD version of Z3 (commit 3b70dd6678ecd307d1e13b89596ec1f57c0c5aff) and it was gone. This would explain the rise4fun results. I think they are runing a newer version. Version 4.1.1 was build last year. There are more than 1.5k commits since then in the Z3 repository...

Here the test result.
SAT
x:=1.0,y:=1.5,z:=2.0
(((('y' < 'z') && ('y' > 'x')) && ('x' == 1.0)) && ('z' == 2.0))

**Comment by fhowar** [comment]
I tried what @mmuesly  suggested. I fixes the problem. 

BUT:

I requires some changes to the code of jconstraints-z3. E.g., it seems that disposing of objects is no longer necessary.

How do we deal with this? Depending on HEAD of z3 is not the best idea as it changes frequently. Thoughts?

**Comment by ksluckow** [comment]
It is not completely clear to me (I didn't have time to test it carefully), but is the problem because of the initial push that is made by jconstraints when adding the constraint? Can we simply fix the bug by omitting the initial push?
Alternatively, we can make integrate (and support) a recent commit of z3 where the bug has been fixed. It will require some work to accommodate the automatic disposal of objects etc. I just suspect that we will need to fix quite a lot if we want to support a future release of z3.

**Comment by ksluckow** [comment]
It is not completely clear to me (I didn't have time to test it carefully), but is the problem because of the initial push that is made by jconstraints when adding the constraint? Can we simply fix the bug by omitting the initial push?
Alternatively, we can make integrate (and support) a recent commit of z3 where the bug has been fixed. It will require some work to accommodate the automatic disposal of objects etc. I just suspect that we will need to fix quite a lot if we want to support a future release of z3.

**Comment by fhowar** [comment]
I pushed a tentative fix (see above). It requires creating a fresh context for every invocation of solve. 

I also created a new branch (z3head) that works with a recent commit to z3.

I think we should leave it at that for now and update to a release of z3 once there is a new one.

The fix affects performance significantly in cases where many calls to solve are made.

**Comment by ksluckow** [comment]
That's great! It makes good sense to support both.
